### ISSUE TITLE
not writing to table

### ISSUE THREAD

**Issue by eman1986** [saleem-mirza/serilog-sinks-mysql#10]
I got everything setup, but its not writing to the table.

`var logger = new LoggerConfiguration()
                .WriteTo.MySQL("MyConnectionString")
                .CreateLogger();`

I'm using it in a net standard app if that makes a difference, I see you have netstandard support so that shouldn't be an issue.

**Comment by undauntedspirit** [comment]
Can confirmed my samples do the same thing -- successfully creates the table but fails to ever write any data to the table.

**Comment by saleem-mirza** [comment]
@undauntedspirit, I'm not able to reproduce issue. Please create defect with testable solution.
