### ISSUE TITLE
Ability to add custom columns

### ISSUE THREAD

**Issue by calvinypark** [saleem-mirza/serilog-sinks-mysql#11]
I think MSSQL sink allows this, but, having the ability to add additional custom columns would be beneficial in organizing and logging more information.  This should either be set as a configuration syntax in C# or configuration fields in appsettings.json.

**Comment by calvinypark** [comment]
I'm actually modifying this code to set additional columns, but, I realize that Serilog.LogEvent also needs to be updated to allow this.

**Comment by saleem-mirza** [comment]
You can store additional Fields as log properties. Properties column will have JSON structure. I don't see any value to modify logging framework just to store additional information in different format.

**Comment by calvinypark** [comment]
I ended up modifying the source code to create additional columns and insert into them.  Not the cleanest solution, but, it works!

**Comment by PsiRadish** [comment]
It's only why at least 4 alternative packages to this one exist, but sure; no value to it whatsoever.
