### ISSUE TITLE
Mismatch with SQL Server Field

### ISSUE THREAD

**Issue by renxuefeng** [saleem-mirza/serilog-sinks-mysql#14]
Serilog.Sinks.MSSqlServer One of the fields in SQL Server is "MessageTemplate"
serilog-sinks-mysql  One of the fields in Mysql is "template"
So it's not universal.

**Comment by saleem-mirza** [comment]
Sinks were developed and maintained by different folks and now it's too late to make breaking changes. Both sinks are being actively used.
