### ISSUE TITLE
Log entries not written

### ISSUE THREAD

**Issue by SuperJMN** [saleem-mirza/serilog-sinks-mysql#4]
I'm trying with this code:

```
var logger = new LoggerConfiguration()
    .WriteTo.MySQL("server=raspberrypi;uid=user;pwd=somePwd;database=diagnostics;SslMode=None")
    .CreateLogger();

logger.Information("This informational message will be written to MySQL database");
```

The table is created, but no log entry is written. How can this be? The user in the connection string has DB owner access (can do anything).

NOTICE that I'm using this package: https://www.nuget.org/packages/Serilog.Sinks.MySQL.NetCore2/ because I'm using it in a .NET Core 2 Application.

Thanks in advance for your help!

**Comment by saleem-mirza** [comment]
This logger doesn't support .net core yet. It's working as expected with .Net Framework 4.5.1 and above.

**Comment by SuperJMN** [comment]
OK, but I've found the NuGet package for .NET Core. Please, check the [link](https://www.nuget.org/packages/Serilog.Sinks.MySQL.NetCore2/). Do you know where is the GitHub repository for it? It seems that you're also the author :)

**Comment by saleem-mirza** [comment]
Not sure. Probably someone is using my name. Hey thanks for bringing it up. I'll check with nuget.

**Comment by saleem-mirza** [comment]
Here it goes. https://github.com/reinaldocoelho

**Comment by SuperJMN** [comment]
You're welcome! Maybe it's just somebody that wanted support for .NET Core, like me, and ported the bits :) Please, add "oficial" support. I'm already using the package I mentioned and it's working, the problem is that it buffers all the log entries for some seconds, until it actually sends a bulk insert to the DB. The console program I used to test ended prematurely, so no log entry was sent to the DB.

**Comment by saleem-mirza** [comment]
@SuperJMN. I have added support for .net standard 1.3
Please see https://www.nuget.org/packages/Serilog.Sinks.MySQL/2.7.5-dev-00030. Let me know if it works.

**Comment by SuperJMN** [comment]
Hey @saleem-mirza ! I have tried your new version. Thanks for making it .NET Standard compliant! 

But there's a problem. It seems it has the same problem I told you about.

I had the problem with my application and your log sink: when the application has a problem, in the catch block, I log the error with Log.Error, but the log entry isn't written in the MySQL table, because the app terminates before the "log buffer" has been flushed to the DB. This results in missing entries that are crucial for detecting problems (the error isn't even logged).

You can check it by creating a simple console program with the lines that I posted above.

**Comment by saleem-mirza** [comment]
Well, I'm not sure any logger will work if you application suddenly crash.  However, try limiting `batchSize` to 1 (default is 100). This will prevent logger from batching of messages.

Please let me know if this helps.
