### ISSUE TITLE
MySql Sink Documentation

### ISSUE THREAD

**Issue by dapedley** [saleem-mirza/serilog-sinks-mysql#5]
Hi Saleem. Is there any documentation for the MySql sink for net core 2, please (can't find any)?
In particular, do I need to define a MySql table for logs (definition?) or can it be generated automatically?

**Comment by saleem-mirza** [comment]
Please see https://github.com/saleem-mirza/serilog-sinks-mysql/blob/dev/README.md for documentation. 

Table name is optional. If you don’t provide one, it will create one with name “Logs”. 

Please see parameters for sinks.

**Comment by dapedley** [comment]
Hi Saleem. Thanks for that. I have now got it working.
Is there any way to clear the database log table on creation in Main and before running Configure (net core 2), in order to log any early errors. For instance, can you access a connection that the Logger uses? In a development situation, one probably wants to just see the log for the last test run. I use EF in the app, to access the database which seems to create a conflict in MySqlConnection when trying to use the MySqlClient directly (which would otherwise be fairly simple). To fire up EF prior to Configuration, create a model for the table and a context is rather messy.
