### ISSUE TITLE
Is it possible to add MachineName to the column output to MySQL Logs table using the appsetting.json config file?

### ISSUE THREAD

**Issue by paulandrewconway** [saleem-mirza/serilog-sinks-mysql#9]

**Comment by eman1986** [comment]
that would be a needed thing for me as well, most of the websites my team works on are load balanced so we need to know which server its logging from.

**Comment by eman1986** [comment]
looks like you'd need to use Serilog.Enrichers.Environment but not sure how'd you use it alongside this sink.

**Comment by saleem-mirza** [comment]
Enrichers are way to go.

Please see https://github.com/saleem-mirza/serilog-enrichers-context
